# Generated by Django 4.2.6 on 2023-10-21 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portscan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=16, verbose_name='关键词')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='PortResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('open_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='webSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64, verbose_name='监测的网站地址')),
                ('title', models.CharField(default='未捕获', max_length=64, verbose_name='网站标题')),
                ('bef_long', models.IntegerField(blank=True, null=True, verbose_name='之前字节长度')),
                ('aft_long', models.IntegerField(verbose_name='当前字节长度')),
                ('respond_code', models.SmallIntegerField(verbose_name='网页状态')),
                ('owner', models.CharField(default='暂无', max_length=10, verbose_name='责任人')),
                ('keyword', models.IntegerField(default=0, verbose_name='触发关键词数量')),
                ('status', models.SmallIntegerField(choices=[(0, '停止监控'), (1, '正常'), (2, '异常')], verbose_name='当前状态')),
            ],
        ),
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.SmallIntegerField(choices=[(0, 'Linux'), (1, 'Windows'), (2, 'Other')], verbose_name='系统类型')),
                ('os_release', models.CharField(max_length=64)),
                ('cpu_count', models.SmallIntegerField(blank=True, null=True, verbose_name='CPU总数')),
                ('cpu_model', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255, verbose_name='型号')),
                ('mac', models.CharField(max_length=64, verbose_name='MAC地址')),
                ('nic_count', models.SmallIntegerField(default=1, verbose_name='网卡总数')),
                ('status', models.SmallIntegerField(choices=[(0, '过期'), (1, '最新')], default=0, verbose_name='更新状态')),
                ('firewall', models.SmallIntegerField(default=0, verbose_name='防火墙状态')),
                ('device_id', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='portscan.ips')),
            ],
        ),
    ]
