# Generated by Django 4.2.6 on 2023-10-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vulList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='漏洞名称')),
                ('cve', models.CharField(blank=True, max_length=32, null=True, verbose_name='CVE漏洞编号')),
                ('methodName', models.CharField(blank=True, max_length=32, null=True, verbose_name='对应方法名')),
            ],
        ),
    ]
