# Generated by Django 4.2.6 on 2023-10-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('online', models.BooleanField(default=False)),
                ('owner', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('remove', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='license',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_time', models.CharField(max_length=11, verbose_name='过期时间')),
                ('license_key', models.CharField(max_length=64, verbose_name='密钥')),
                ('status', models.SmallIntegerField(choices=[(0, '失效'), (1, '激活')], verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=128, null=True, verbose_name='设置的值，可为空')),
            ],
        ),
        migrations.CreateModel(
            name='vulList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='漏洞名称')),
                ('cve', models.CharField(blank=True, max_length=32, null=True, verbose_name='CVE漏洞编号')),
                ('methodName', models.CharField(blank=True, max_length=32, null=True, verbose_name='对应方法名')),
            ],
        ),
    ]
